import test from 'node:test';import assert from 'node:assert/strict';import {whatsappInbound} from './whatsapp-inbound.mjs';
async function signature(text){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode('synthetic-test-secret'),{name:'HMAC',hash:'SHA-256'},false,['sign']);return 'sha256='+Buffer.from(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(text))).toString('hex');}
function setup(){const messages=new Map();const store={resolveChannelMembership:async x=>x.businessAccountId==='account-a'&&x.businessNumberId==='number-a'&&x.senderId==='enrolled-sender'?{clientId:'client-a',requestId:'request-a'}:null,appendInboundOnce:async(a,m)=>{messages.set(m.businessAccountId+'/'+m.providerMessageId,{actor:a,event:m});}};return {adapter:whatsappInbound({appSecret:'synthetic-test-secret',verifyToken:'synthetic-verify',businessNumberId:'number-a',store}),messages};}
const payload=(sender='enrolled-sender',number='number-a',type='text')=>JSON.stringify({object:'whatsapp_business_account',entry:[{id:'account-a',changes:[{value:{metadata:{phone_number_id:number},messages:[{id:'synthetic-id',from:sender,type,timestamp:'1',text:{body:'Review the website'}}]}}]}]});
async function req(body,signed=true){return new Request('https://webhook.example.test/',{method:'POST',body,headers:{'X-Hub-Signature-256':signed?await signature(body):'sha256='+'0'.repeat(64)}});}
test('unsigned and forged webhook denied',async()=>{const {adapter,messages}=setup();assert.equal((await adapter.handle(await req(payload(),false))).status,403);assert.equal(messages.size,0)});
test('signed enrolled sender recorded with server scope and dedup',async()=>{const {adapter,messages}=setup();assert.equal((await adapter.handle(await req(payload()))).status,200);await adapter.handle(await req(payload()));assert.equal(messages.size,1);const m=[...messages.values()][0];assert.equal(m.actor.requestId,'request-a');assert.equal(m.event.channel,'WhatsApp')});
test('wrong destination unknown sender and attachment ignored',async()=>{const {adapter,messages}=setup();for(const x of [payload('unknown'),payload('enrolled-sender','wrong-number'),payload('enrolled-sender','number-a','image')])assert.equal((await adapter.handle(await req(x))).status,200);assert.equal(messages.size,0)});
test('verification token required, no unsolicited connection',async()=>{const {adapter}=setup();assert.equal((await adapter.handle(new Request('https://x.test/?hub.mode=subscribe&hub.verify_token=bad'))).status,403);assert.equal(await (await adapter.handle(new Request('https://x.test/?hub.mode=subscribe&hub.verify_token=synthetic-verify&hub.challenge=123'))).text(),'123')});
