// Configuration must be generated server-side after verified membership. Public demo stays disconnected.
(async()=>{
const state=document.getElementById('chat-state'),form=document.getElementById('chat-form'),input=document.getElementById('message'),send=document.getElementById('send'),log=document.getElementById('conversation');
let config=window.RFI_CHAT;
if(!config){try{const r=await fetch('/api/session',{credentials:'same-origin',headers:{Accept:'application/json'}});if(!r.ok)return;const session=await r.json();if(session.requests?.length!==1){state.textContent='Select a client request in your authenticated workspace before chatting.';return;}config={requestId:session.requests[0].id,enabled:session.enabled};}catch{return;}}
if(!config?.requestId){state.textContent='No authorized request selected.';return;}
const base='/api/requests/'+encodeURIComponent(config.requestId);
function message(role,body){let p=document.createElement('p');p.style.whiteSpace='pre-wrap';p.textContent=(role==='user'?'You: ':'Assistant: ')+body;log.append(p);}
try{const response=await fetch(base+'/history',{credentials:'same-origin',headers:{Accept:'application/json'}});if(!response.ok)throw Error('Authenticated chat is unavailable. Sign in with your authorized client account.');const data=await response.json();for(const item of data.messages||[])message(item.role,item.body);if(!config.enabled){send.textContent='Save review note';document.getElementById('chat-title').textContent='Project discussion';}input.disabled=false;send.disabled=false;input.placeholder='Ask about this project or request a change';state.textContent=config.enabled?'Private text-only chat. Proposed changes are not approvals.':'Leave a non-sensitive website-review note. It is saved to this project, not sent to AI. A reviewer must confirm changes.';}catch(e){state.textContent=e.message;return;}
form.addEventListener('submit',async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;send.disabled=true;input.disabled=true;state.textContent=config.enabled?'Sending to the assistant...':'Saving your review note...';try{const response=await fetch(base+(config.enabled?'/chat':'/notes'),{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});const data=await response.json();if(!response.ok)throw Error(data.error||'Message was not accepted.');message('user',text);if(config.enabled)message('assistant',data.reply);else if(!data.saved||data.ai!==false)throw Error('Save could not be confirmed.');input.value='';state.textContent=config.enabled?'Reply received. Suggested changes need confirmation and reviewer checks.':'Review note saved. No AI reply or approval was made.';}catch(e){state.textContent=e.message+' Your message remains in the box.';}finally{input.disabled=false;send.disabled=false;}});
})();
