// Configuration must be generated server-side after verified membership. Public demo stays disconnected.
(async()=>{
const state=document.getElementById('chat-state'),form=document.getElementById('chat-form'),input=document.getElementById('message'),send=document.getElementById('send'),log=document.getElementById('conversation');
const config=window.RFI_CHAT;if(!config||!config.requestId||!config.enabled){return;}
const base='/api/requests/'+encodeURIComponent(config.requestId);
function message(role,body){let p=document.createElement('p');p.style.whiteSpace='pre-wrap';p.textContent=(role==='user'?'You: ':'Assistant: ')+body;log.append(p);}
try{const response=await fetch(base+'/history',{credentials:'same-origin',headers:{Accept:'application/json'}});if(!response.ok)throw Error('Authenticated chat is unavailable. Sign in with your authorized client account.');const data=await response.json();for(const item of data.messages||[])message(item.role,item.body);input.disabled=false;send.disabled=false;state.textContent='Private text-only chat. Messages are saved to this request; proposed changes are not approvals.';}catch(e){state.textContent=e.message;return;}
form.addEventListener('submit',async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;send.disabled=true;input.disabled=true;state.textContent='Sending to the assistant...';try{const response=await fetch(base+'/chat',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});const data=await response.json();if(!response.ok)throw Error(data.error||'Message was not accepted.');message('user',text);message('assistant',data.reply);input.value='';state.textContent='Reply received. Suggested changes need confirmation and reviewer checks.';}catch(e){state.textContent=e.message+' Your message remains in the box.';}finally{input.disabled=false;send.disabled=false;}});
})();
