import test from 'node:test';import assert from 'node:assert/strict';
import {createService} from './service.mjs';import {MemoryStore} from './memory-store.mjs';import {freeRouter} from './free-router.mjs';
function setup(options={}){const store=new MemoryStore({memberships:{alice:{a:{clientId:'one',role:'client',aiConsentAt:1}},bob:{b:{clientId:'two',role:'client',aiConsentAt:1}}}});const model={reply:async()=> 'Which part of the website should we update?'};const service=createService({auth:{verify:async r=>({subject:r.headers.get('X-Test-Subject')})},store,model,origin:'https://app.test',chatEnabled:true,...options});return {store,service};}
const request=(id,subject,body,origin='https://app.test')=>new Request('https://app.test/api/requests/'+id+'/'+(body===undefined?'history':'chat'),{method:body===undefined?'GET':'POST',headers:{'X-Test-Subject':subject||'',Origin:origin,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
test('signed identity adapter must return subject',async()=>{const {service}=setup();assert.equal((await service.handle(request('a',''))).status,401)});
test('wrong client cannot read or post',async()=>{const {service}=setup();for(const body of [undefined,{message:'hello'}])assert.equal((await service.handle(request('a','bob',body))).status,403)});
test('own client exchanges and history remain isolated',async()=>{const {service}=setup();const sent=await service.handle(request('a','alice',{message:'Can we update website colors?'}));assert.equal(sent.status,200);const own=await (await service.handle(request('a','alice'))).json();const other=await (await service.handle(request('b','bob'))).json();assert.equal(own.messages.length,2);assert.equal(other.messages.length,0);assert.equal(own.messages[1].role,'assistant')});
test('origin rejected before model',async()=>{const {service}=setup({model:{reply(){throw Error('Must not call')}}});assert.equal((await service.handle(request('a','alice',{message:'hello'},'https://attacker.test'))).status,403)});
test('images attachments tools arrays and secrets rejected',async()=>{const {service}=setup();for(const body of [{message:'hi',images:['x']},{message:'hi',tools:[]},{message:'hi',attachments:[]},[],null])assert.equal((await service.handle(request('a','alice',body))).status,400);assert.equal((await service.handle(request('a','alice',{message:'password: demo-only'}))).status,422)});
test('daily quota has no paid fallback',async()=>{const {service}=setup({dailyCap:1});assert.equal((await service.handle(request('a','alice',{message:'first'}))).status,200);assert.equal((await service.handle(request('a','alice',{message:'second'}))).status,429)});
test('chat requires consent and configured enable',async()=>{const {service}=setup({chatEnabled:false});assert.equal((await service.handle(request('a','alice',{message:'hello'}))).status,503)});
test('actual bytes bounded without declared length',async()=>{const {service}=setup();assert.equal((await service.handle(request('a','alice',{message:'a'.repeat(25000)}))).status,413)});
test('model failure not saved as successful conversation',async()=>{const {service,store}=setup({model:{reply:async()=>{throw Error('down')}}});assert.equal((await service.handle(request('a','alice',{message:'hello'}))).status,503);assert.equal(store.messages.size,0)});
test('oversize response rejected',async()=>{const {service}=setup({model:{reply:async()=> 'x'.repeat(8001)}});assert.equal((await service.handle(request('a','alice',{message:'hello'}))).status,503)});
test('router contract gate explicit',()=>assert.throws(()=>freeRouter({url:'https://router.test',key:'synthetic'})));
test('free router sends metadata realtime and no tools/images',async()=>{let data;const adapter=freeRouter({url:'https://router.test',key:'synthetic',contractVerified:true,decodeResponse:x=>x.text,fetchImpl:async(u,r)=>{data=JSON.parse(r.body);return Response.json({text:'reply'})}});assert.equal(await adapter.reply({message:'hello'}),'reply');assert.equal(data.force_tier,'free');assert.equal(data.metadata.request_type,'realtime');assert.equal(data.request_type,undefined);assert.equal(data.images,undefined);assert.equal(data.tools,undefined)});
test('non-AI review note saves under scope, blocks CSRF/secrets/other client and makes no model call',async()=>{
 let saved=[],calls=0;const svc=createService({auth:{verify:async()=>({subject:'alice@example.test'})},store:{resolveMembership:async(s,id)=>id==='own'?{clientId:'a',role:'client'}:null,reserveQuota:async()=>true,appendNote:async(a,n)=>saved.push({a,n})},model:{reply:async()=>{calls++;throw Error('Forbidden model')}},origin:'https://private.test',chatEnabled:false});
 const req=(id='own',body='Please review the business form',origin='https://private.test')=>new Request('https://private.test/api/requests/'+id+'/notes',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({message:body})});
 const r=await svc.handle(req());assert.equal(r.status,200);assert.deepEqual(await r.json(),{saved:true,body:'Please review the business form',review_state:'pending',ai:false});assert.equal(saved.length,1);assert.equal(calls,0);assert.equal(saved[0].a.subject,'alice@example.test');assert.equal((await svc.handle(req('other'))).status,403);assert.equal((await svc.handle(req('own','hello','https://evil.test'))).status,403);assert.equal((await svc.handle(req('own','password=secret'))).status,422);assert.equal(saved.length,1);
});
